USE bdFiliados

SELECT * FROM dbo.Filiados_PTC

--1
SELECT NOME_DO_FILIADO FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

--2
SELECT NOME_DO_FILIADO FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE '%SEBASTIAO%'

--3
SELECT NOME_DO_FILIADO FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE '%OS'

--4
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'SÃO FÉLIX'

--5
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'INHAMBUPE'

--6
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%'

--7
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

--8
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'

--9
SELECT NOME_DO_FILIADO, NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%DE%'

--10
SELECT NOME_DO_FILIADO, DATA_DA_FILIACAO FROM dbo.Filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '01/01/1990' AND '01/01/2000'

--11
SELECT NOME_DO_FILIADO, DATA_DA_FILIACAO FROM dbo.Filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010' AND '01/03/2010'

--12 
SELECT NOME_DO_FILIADO, SIGLA_DO_PARTIDO, DATA_DA_FILIACAO FROM dbo.fILIADOS_PTC
WHERE SIGLA_DO_PARTIDO = 'PTC'AND DATA_DA_FILIACAO BETWEEN '01/07/2007' AND '31/12/2007'

--13
SELECT NOME_DO_FILIADO, SITUACAO_DO_REGISTRO FROM dbo.Filiados_PTC
WHERE SITUACAO_DO_REGISTRO LIKE '%REGULAR%'

--14
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL = 203

--15
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL = 180

--16
SELECT NOME_DO_FILIADO, ZONA_ELEITORAL FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL = 199

--17
SELECT MAX (ZONA_ELEITORAL) FROM dbo.Filiados_PTC

--18
SELECT MIN (ZONA_ELEITORAL) FROM dbo.Filiados_PTC

