USE bdFiliados

SELECT * FROM dbo.Filiados_PTC

--19
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO = 'PT'
WHERE CODIGO_DO_MUNICIPIO = 36471

--20
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO = 'PMDB'
WHERE CODIGO_DO_MUNICIPIO = 38490

--21
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO = 'PC'
WHERE NOME_DO_MUNICIPIO LIKE 'SANTANÓPOLIS'

--22
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO = 'PV', NOME_DO_PARTIDO = 'Partido Verde'
WHERE NOME_DO_MUNICIPIO LIKE 'São Félix'

--23
UPDATE dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO = 'PSDB', NOME_DO_PARTIDO = 'Partido da Social Democracia Brasileira'
WHERE NOME_DO_MUNICIPIO LIKE 'ENCRUZILHADA'

--24
UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO LIKE 'JORGE LUIS FERREIRA DOS SANTOS'

--25
UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUES'
WHERE NOME_DO_FILIADO LIKE 'BENTA XAVIER RODRIGUES'

--26
UPDATE dbo.Filiados_PTC
SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO LIKE 'NOE LEITE DA SILVA'

--27
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

--28
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'

--29
UPDATE dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'

--30
ALTER TABLE dbo.Filiados_PTC ADD SEXO_DOS_FILIADOS CHAR(1) NULL

